// To mimic the snake game we played when we were younger,
// but built in Assembly

// BuildLevel # i.e., walls
@BUILD_BORDER
0;JMP
@END

(END)
  @2
  0;JMP

(BUILD_BORDER)
  @INITIALIZE_TOP_BORDER
  @INITIALIZE_BOTTOM_BORDER

(INITIALIZE_TOP_BORDER)
  @SCREEN // Furthest top left RAM
  D=A
  @CURRENT_POSITION
  M=D
  @16415 // Furthest top right RAM
  D=A
  @TOP_RIGHT_CORNER
  M=D
  // @TOP_BORDER_VALUE
  // M=-1
  @DRAW_TOP_BORDER
  0;JMP

(DRAW_TOP_BORDER)
  @CURRENT_POSITION
  A=M
  M=-1
  @TOP_RIGHT_CORNER
  D=M
  @CURRENT_POSITION
  M=M+1
  D=M-D
  @DRAW_TOP_BORDER
  D;JLE
  @INITIALIZE_BOTTOM_BORDER
  0;JMP

(INITIALIZE_BOTTOM_BORDER)
  @24544 // Furthest bottom left RAM
  D=A
  @CURRENT_POSITION
  M=D
  @24575 // Furthest bottom right RAM
  D=A
  @BOTTOM_RIGHT_CORNER
  M=D
  // @BOTTOM_BORDER_VALUE
  // M=-1
  @DRAW_BOTTOM_BORDER
  0;JMP

(DRAW_BOTTOM_BORDER)
  @CURRENT_POSITION
  A=M
  M=-1
  @BOTTOM_RIGHT_CORNER
  D=M
  @CURRENT_POSITION
  M=M+1
  D=M-D
  @DRAW_BOTTOM_BORDER
  D;JLE
  // DRAW LEFT BORDER
  @END
  0;JMP